/**
 * src/routes/RouteWrapper.jsx
 */


import { useState, useEffect, lazy, Suspense } from 'react'
import moduleLoaders from '../moduleLoaders'
import { throbber, Throbber } from '../component/Throbber'


const lazyCache = new Map()


// Don't reload a module if it is already cached
export function getLazyModule(path) {
  let Module = lazyCache.get(path)

  if (!Module) {

    let loader = moduleLoaders[path] // () => import("...")

    if (!loader) {
      // throw error with explicit message for ErrorBoundary
      throw new Error(`loader missing for ${path}`)
    }

    // <<< TEMP TEST during development. Remove for production.
    if (path === "./modules/__NetworkError__.jsx") {
      loader = simulateNetworkError() // () => (rejected promise)
    }
    // TEMP TEST >>>

    const importer =
      loader()
      .catch(error => {
        // Remove from cache so future attempts can retry
        console.error(error)
        lazyCache.delete(path)
        throw error
      })

    Module = lazy(() => importer)

    lazyCache.set(path, Module)
  }

  return Module
}


export const RouteWrapper = (props) => {
  const { path, setRouteAndLabel } = props // + label, route
  const [ LazyModule, setLazyModule ] = useState(
    () => () => <Throbber />
  )

  const loadModule = () => {
    setRouteAndLabel(props)
    const Module = getLazyModule(path)

    if (Module) {
      setLazyModule(Module)
    }
  }


  useEffect(loadModule, [path])


  return (
    <Suspense fallback={throbber}>
      <LazyModule {...props} />
    </Suspense>
  )
}



/**
 * For testing purposes during development
 * @returns a promise which rejects with an error typical of
 *          an error generated by a real network error.
 */
const simulateNetworkError = () => {
  const errors = [
    // Chrome, Edge, Safari
    "Failed to fetch dynamically imported module",
    // Firefox
    "NetworkError when attempting to fetch resource."
  ]
  const index = Math.floor(Math.random() * errors.length)
  const errorMessage = errors[index]

  return () => new Promise((resolve, reject) => {
    setTimeout(() => {
      const error = new TypeError(errorMessage)
      reject(error)
    }, 1000)
  })
}
